<template>
  <div>
    <HomeHero></HomeHero>
    <CategoryGrid></CategoryGrid>
    <BestSellers></BestSellers>
    <WhyUs></WhyUs>
    <ReviewsSection></ReviewsSection>
    <StoreLocation></StoreLocation>
    <AppFooter></AppFooter>
    <WhatsAppButton></WhatsAppButton>
  </div>
</template>
